"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    sidebar: {
      feed: "Bảng tin",
      discover: "Khám phá",
      favorites: "Yêu thích",
      history: "Lịch sử",
      recommendations: "Gợi ý cho bạn",
      collections: "Bộ sưu tập",
      luckyWheel: "Hôm nay ăn gì?",
      friends: "Bạn bè",
      settings: "Cài đặt",
      itinerary: "Lộ trình",
      groupRecommend: "Gợi ý nhóm",
      aiTitle: "AI Wanderbite",
      aiDesc: "Để AI hiểu bạn hơn, hãy cập nhật sở thích thường xuyên nhé!",
      aiBtn: "Cập nhật ngay",
      guest: "Khách",
      member: "Thành viên",
    },
    appshell: {
      locationTitle: "Nhấp để thay đổi vị trí của bạn",
      notPositioned: "Chưa định vị",
      finding: "Đang tìm...",
      systemOk: "Hệ thống bình thường",
      systemError: "Hệ thống có vấn đề",
      sessionExpired: "Phiên Hết Hạn",
      sessionExpiredDesc: "Phiên đăng nhập của bạn đã hết hạn hoặc không hợp lệ. Vui lòng đăng nhập lại để sử dụng đầy đủ các tính năng cá nhân hóa!",
      goHome: "Quay lại trang chủ",
      loginAgain: "Đăng nhập lại",
      drawerTitle: "Wanderbite",
      drawerFooter: "Gợi ý bởi AI · Vị ngon Sài Gòn",
      openMenu: "Mở menu",
      itineraryTitle: "Xem lộ trình",
      notLocatedYet: "Chưa định vị",
    },
    settings: {
      title: "Cài đặt",
      tabAccount: "Tài khoản",
      tabPersonalization: "Cá nhân hóa",
      tabAppearance: "Giao diện",
      tabPrivacy: "Quyền riêng tư",
      accountDesc: "Quản lý thông tin tài khoản và bảo mật.",
      appearanceDesc: "Tùy chỉnh giao diện ứng dụng theo sở thích.",
      theme: "Giao diện",
      themeDesc: "Tùy chỉnh giao diện ứng dụng theo sở thích.",
      themeLight: "Sáng",
      themeDark: "Tối",
      themeSystem: "Hệ thống",
      themeLightDesc: "Trải nghiệm sáng",
      themeDarkDesc: "Dễ nhìn ban đêm",
      themeSystemDesc: "Theo cài đặt máy",
      language: "Ngôn ngữ",
      langVi: "Tiếng Việt",
      langEn: "English",
      save: "Lưu",
      cancel: "Hủy",
      languageTitle: "Ngôn ngữ",
      languageSelectDesc: "Chọn ngôn ngữ hiển thị của ứng dụng.",
      savingInProgress: "Đang đồng bộ...",
      updatePreferencesSuccess: "Cập nhật sở thích AI thành công!",
      updatePreferencesFailed: "Cập nhật thất bại!",
      savingError: "Có lỗi xảy ra khi lưu!",
      favoriteDishesLabel: "Món ăn yêu thích (Chọn hoặc tự nhập ít nhất 3 món)",
      spicyLabel: "Độ cay ưu tiên",
      budgetLabel: "Mức giá trung bình",
      dietaryLabel: "Chế độ ăn kiêng",
      allergyLabel: "Dị ứng thực phẩm",
      locationLabel: "Khu vực sinh sống",
      ageLabel: "Độ tuổi",
      popularSuggestions: "Gợi ý phổ biến:",
      placeholderAge: "Nhập tuổi...",
      placeholderLocation: "Ví dụ: Quận 1, TP. HCM...",
      placeholderDish: "Nhập tên món ăn ví dụ: Bún chả...",
      aiPersonalizationTitle: "Cá nhân hóa AI",
      aiPersonalizationDesc: "Thiết lập sở thích ăn uống để AI gợi ý chuẩn vị nhất cho bạn.",
      syncWithAI: "Cập nhật sở thích AI",
      addDishBtn: "Thêm",
      dishAlreadyAdded: "Món ăn này đã có trong danh sách!",
      atLeastThreeDishes: "Vui lòng chọn hoặc tự nhập ít nhất 3 món ăn yêu thích!",
      selectSpicy: "Vui lòng chọn mức độ cay!",
      selectBudget: "Vui lòng chọn ngân sách!",
      enterLocation: "Vui lòng điền khu vực sinh sống!",
      invalidAge: "Độ tuổi chưa hợp lệ (13 - 120)!",
      featuresUnderDevelopmentTitle: "Tính năng đang phát triển",
      featuresUnderDevelopmentDesc: "Tính năng này sẽ sớm ra mắt!",
      editCoverTitle: "Chỉnh sửa ảnh bìa",
      editCoverDesc: "Phóng to, xoay hoặc kéo ảnh để căn giữa vùng cắt chữ nhật (tỷ lệ 3:1).",
      zoom: "Thu phóng",
      rotate: "Xoay ảnh",
      confirmCrop: "Xác nhận cắt",
      editAvatarTitle: "Chỉnh sửa ảnh đại diện",
      editAvatarDesc: "Phóng to, xoay hoặc kéo ảnh để căn giữa vùng cắt hình tròn.",
      changePassword: "Đổi mật khẩu",
      changePasswordDesc: "Vui lòng nhập mật khẩu hiện tại và mật khẩu mới của bạn.",
      currentPassword: "Mật khẩu hiện tại",
      newPassword: "Mật khẩu mới",
      confirmNewPassword: "Xác nhận mật khẩu mới",
      updateBtn: "Cập nhật",
      confirmDeleteTitle: "Xác nhận xóa tài khoản?",
      confirmDeleteDesc: "Hành động này không thể hoàn tác. Tất cả dữ liệu, lịch sử và tùy chỉnh của bạn sẽ bị xóa vĩnh viễn khỏi hệ thống.",
      confirmDeleteBtn: "Xác nhận xóa",
      selectAvatarTitle: "Chọn ảnh đại diện",
      uploadPhotoBtn: "Tải ảnh lên",
      uploadedPhotos: "Ảnh đã tải lên",
      noUploadedPhotos: "Bạn chưa đăng bức ảnh đại diện nào trước đây.",
      viewMore: "Xem thêm",
      accountTitle: "Tài khoản",
      accountSubtitle: "Quản lý thông tin tài khoản và bảo mật.",
      coverPhoto: "Ảnh bìa",
      noCoverPhoto: "Chưa có ảnh bìa",
      changeCoverBtn: "Thay đổi ảnh bìa",
      coverRules: "JPG, PNG tối đa 5MB. Tỷ lệ chuẩn 3:1.",
      avatarLabel: "Ảnh đại diện",
      avatarRules: "JPG, PNG tối đa 5MB",
      changeAvatarBtn: "Thay đổi ảnh",
      editBtn: "Chỉnh sửa",
      fullNameLabel: "Họ và tên",
      fullNamePlaceholder: "Nhập họ và tên...",
      saveBtn: "Lưu",
      copied: "Đã chép",
      copy: "Sao chép",
      googleLinkedAccount: "Tài khoản liên kết Google",
      googleLinkedAccountDesc: "Bạn đang sử dụng tài khoản liên kết Google. Mọi cài đặt bảo mật và quản lý tài khoản sẽ được thực hiện tại trang cá nhân Google của bạn.",
      changePasswordSubtitle: "Cập nhật mật khẩu định kỳ để bảo vệ tài khoản.",
      deleteAccountSubtitle: "Hành động này không thể hoàn tác. Tất cả dữ liệu của bạn trên hệ thống sẽ bị xóa vĩnh viễn.",
      privacyTitle: "Quyền riêng tư",
      privacySubtitle: "Quản lý quyền và dữ liệu cá nhân của bạn.",
      allowLocation: "Cho phép truy cập vị trí",
      allowLocationDesc: "Wanderbite cần quyền này để gợi ý món ăn gần bạn.",
      allowAIPersonalization: "Cho phép dùng dữ liệu cá nhân hóa AI",
      allowAIPersonalizationDesc: "Giúp AI hiểu bạn hơn để đưa ra gợi ý chính xác và phù hợp.",
      featureComingSoon: "Tính năng này sẽ sớm ra mắt",
      dietaryVegan: "Thuần chay",
      dietaryVegetarian: "Ăn chay",
      dietaryHalal: "Halal",
      allergyMilk: "Sữa",
      allergyEgg: "Trứng",
      allergyGluten: "Gluten",
      allergySeafood: "Hải sản",
      allergyFish: "Cá",
      allergyPeanut: "Đậu phộng",
      allergySoy: "Đậu nành",
      spicyNone: "0% Cay",
      spicyMild: "25% Cay",
      spicyMedium: "50% Cay",
      spicyHot: "75% Cay",
      spicyExtraHot: "MAX LEVEL",
      budgetLow: "Bình dân",
      budgetLowDesc: "Dưới 50k - Học sinh/Sinh viên",
      budgetMedium: "Tầm trung",
      budgetMediumDesc: "50k - 200k - Ăn ngon, view ổn",
      budgetHigh: "Cao cấp",
      budgetHighDesc: "Trên 200k - Sang trọng, Fine dining",
      pleaseLoginAgain: "Vui lòng đăng nhập lại để thực hiện thay đổi!",
      sessionExpiredAlert: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại!",
      updateProfileFailed: "Cập nhật thất bại!",
      dbSaveError: "Có lỗi xảy ra khi lưu vào Database!",
      deleteAccountFailed: "Xóa tài khoản thất bại!",
      copiedUserId: "Đã sao chép User ID!",
      passwordsDoNotMatch: "Mật khẩu mới và xác nhận mật khẩu không khớp!",
      passwordMinLength: "Mật khẩu phải có ít nhất 8 ký tự!",
      passwordChangeSuccess: "Đổi mật khẩu thành công!",
      deleteAccountSuccess: "Đã xóa tài khoản thành công!",
      maxFileSizeError: "File quá lớn! Vui lòng chọn ảnh dưới 5MB.",
      imageOptimizationError: "Lỗi tối ưu dung lượng ảnh:",
      localStoreError: "Lỗi lưu trữ cục bộ:",
      quotaExceededCleaning: "Lịch sử đầy, tiến hành dọn dẹp dung lượng...",
      cannotWriteLocalStore: "Không thể ghi vào localStorage ngay cả khi đã dọn dẹp!",
      avatarUpdateSuccess: "Đã cập nhật ảnh đại diện thành công!",
      coverUpdateSuccess: "Đã cập nhật ảnh bìa thành công!",
      nameUpdateSuccess: "Đã cập nhật tên thành công!",
      dishAlreadyInList: "Món ăn này đã có trong danh sách!",
      popularSuggestionsLabel: "Gợi ý phổ biến:"
    },
    home: {
      heroTitle: "HÔM NAY BẠN MUỐN ",
      heroTitleSpan: "ĂN GÌ ?",
      heroDesc: "Mô tả cảm giác bạn muốn · AI sẽ gợi ý ngay",
      budgetAuto: "Tự động",
      budgetLow: "Bình dân",
      budgetMedium: "Tầm trung",
      budgetHigh: "Cao cấp",
      luckyWheelBtn: "Hôm nay ăn gì? Thử Vòng Quay May Mắn!",
      feedBannerTitle: "Khám phá Bảng tin 🌟",
      feedBannerDesc: "Tham gia cộng đồng chia sẻ trải nghiệm ẩm thực!",
      recommendationsTitle: "GỢI Ý CHO BẠN",
      seeMore: "Xem thêm",
      noRecommendations: "Chưa có gợi ý nào, hãy thử tìm kiếm!",
      searchingLocation: "Đang xác định vị trí của bạn...",
      searchingAI: "AI đang phân tích khẩu vị của bạn...",
      searchSuccess: "Đã có kết quả! Đang chuyển hướng...",
      searchError: "Không thể xác định vị trí thực tế của bạn. Vui lòng kiểm tra quyền truy cập GPS để tiếp tục.",
      connError: "Lỗi kết nối AI. Vui lòng thử lại.",
      healthError: "Không thể kết nối tới máy chủ. Vui lòng đảm bảo backend đang chạy.",
      healthDegraded: "Hệ thống đang hoạt động một phần — AI Engine chưa sẵn sàng hoặc Database chưa kết nối.",
      healthRetry: "Thử lại",
      describeCravingPlaceholder: "Mô tả cảm giác món ăn bạn thèm (ví dụ: món gì ấm nóng có nước, ngọt thanh xương ống...)",
      trendingBBQ: "Top Quán Nướng",
      trendingLateNight: "Ăn Đêm",
      trendingHealthy: "Đồ ăn Healthy",
      trendingTeaCoffee: "Trà Sữa & Cà Phê",
      trendingBreadsNoodles: "Bánh mì & Bún",
      trendingDimsumHotpot: "Dimsum & Lẩu",
    },
    favorites: {
      pleaseLogin: "Vui lòng đăng nhập để xem yêu thích",
      removedSuccess: "Đã xóa khỏi yêu thích",
      addedSuccess: "Đã thêm vào yêu thích",
      title: "Món ăn yêu thích",
      desc: "Danh sách các món ăn và địa điểm bạn đã lưu lại",
      emptyTitle: "Bạn chưa có món nào trong yêu thích",
      emptyDesc: "Hãy khám phá và lưu lại những món ăn ngon nhé!",
      exploreBtn: "Khám phá ngay",
      pleaseLoginAction: "Vui lòng đăng nhập để sử dụng chức năng này",
      cardDetailError: "Không thể mở chi tiết nhà hàng này. Vui lòng thử lại sau.",
      sampleResultInfo: "Đây là kết quả mẫu. Hãy thử tìm kiếm để xem các nhà hàng thật nhé!",
      alreadyInCollection: "Món ăn này đã có trong bộ sưu tập của bạn.",
      deleteBtn: "Xóa",
    },
    history: {
      pleaseLogin: "Vui lòng đăng nhập để xem lịch sử",
      removedSuccess: "Đã xóa lịch sử",
      clearConfirm: "Bạn có chắc muốn xóa toàn bộ lịch sử tìm kiếm?",
      clearAllSuccess: "Đã xóa toàn bộ lịch sử",
      title: "Lịch sử tìm kiếm",
      desc: "Xem lại các món ăn bạn đã tìm kiếm gần đây",
      clearAllBtn: "Xóa tất cả",
      emptyTitle: "Bạn chưa có lịch sử tìm kiếm",
      emptyDesc: "Hãy thử tìm một món ăn ngon ngay bây giờ!",
      searchNowBtn: "Tìm kiếm ngay",
      budgetLabel: "Ngân sách:",
      budgetAuto: "Tự động",
    },
    collections: {
      pleaseLogin: "Vui lòng đăng nhập để xem bộ sưu tập",
      createSuccess: "Tạo bộ sưu tập thành công",
      deleteSuccess: "Đã xóa bộ sưu tập",
      removeItemSuccess: "Đã xóa khỏi bộ sưu tập",
      backBtn: "Quay lại",
      savedCount: " món ăn đã lưu",
      emptyTitle: "Bộ sưu tập trống",
      emptyDesc: "Bạn chưa lưu món ăn nào vào bộ sưu tập này.",
      exploreBtn: "Khám phá ngay",
      title: "Bộ sưu tập của bạn",
      desc: "Phân loại và lưu trữ các địa điểm ăn uống theo sở thích riêng",
      createBtn: "Tạo bộ sưu tập",
      emptyAllTitle: "Bạn chưa có bộ sưu tập nào",
      emptyAllDesc: "Hãy tạo bộ sưu tập đầu tiên để lưu lại những quán ngon nhé!",
      createNowBtn: "Tạo ngay",
      locationsCount: "địa điểm",
      deleteCollectionTooltip: "Xóa bộ sưu tập",
      createModalTitle: "Tạo bộ sưu tập mới",
      createModalDesc: "Nhập tên bộ sưu tập để lưu trữ các địa điểm yêu thích của bạn.",
      createModalPlaceholder: "VD: Đi ăn cuối tuần, Quán gần trường...",
      cancelBtn: "Hủy",
      createNewBtn: "Tạo mới",
      deleteModalTitle: "Xóa bộ sưu tập",
      deleteModalDesc: "Bạn có chắc chắn muốn xóa bộ sưu tập này không? Hành động này không thể hoàn tác.",
      deleteConfirmBtn: "Xóa bỏ",
      addedSuccess: "Đã thêm vào bộ sưu tập",
      createAndAddedSuccess: "Đã tạo và thêm vào bộ sưu tập",
      addToCollection: "Thêm vào bộ sưu tập",
      selectToSave: "Chọn bộ sưu tập để lưu",
      noCollectionsYet: "Bạn chưa có bộ sưu tập nào.",
      collectionNamePlaceholder: "Tên bộ sưu tập...",
      save: "Lưu",
      alreadyInCollectionCheck: "Đã có trong bộ sưu tập",
    },
    itinerary: {
      directions: "Chỉ đường",
      missingGPSWarning: "Một số địa điểm thiếu toạ độ GPS",
      missingGPSWarningDesc: "khoảng cách sẽ không được hiển thị.",
      stopsCount: "Điểm dừng",
      totalDistance: "Tổng khoảng cách",
      travelTime: "Thời gian di chuyển",
      stopsCountValue: "địa điểm",
      title: "Lộ trình của tôi",
      subtitle: "địa điểm · Kéo để sắp xếp lại",
      clearAll: "Xoá tất cả",
      loading: "Đang tải lộ trình...",
      pleaseWait: "Vui lòng chờ trong giây lát.",
      emptyTitle: "Lộ trình trống",
      emptyDesc: "Nhấn nút 🗺 Lộ trình trên thẻ nhà hàng để thêm điểm đến vào đây.",
      findPlaces: "Tìm địa điểm",
      rainWarning: "⚠️ Cảnh báo mưa tại {count} điểm dừng",
      rainWarningDesc: "đang có mưa hoặc dự kiến mưa. Hãy mang theo áo mưa!",
      checkingWeather: "Đang kiểm tra thời tiết tại các điểm dừng...",
      vehicleLabel: "Phương tiện:",
      walking: "Đi bộ",
      riding: "Xe máy",
      driving: "Ô tô",
      currentLocation: "Vị trí hiện tại của bạn",
      startPoint: "Điểm xuất phát của hành trình",
      missingGPS: "Thiếu GPS",
      deleteStopTitle: "Xoá khỏi lộ trình",
      noDistanceData: "Không có dữ liệu khoảng cách",
      openInGoogleMaps: "Mở lộ trình trong Google Maps",
      openInGoogleMapsDesc: "Sẽ mở toàn bộ lộ trình xuất phát từ vị trí của bạn trên Google Maps",
      clearConfirmTitle: "Xoá lộ trình?",
      clearConfirmDesc: "Toàn bộ {count} địa điểm sẽ bị xoá. Hành động này không thể hoàn tác.",
      cancelBtn: "Huỷ",
    },
    friends: {
      pleaseLogin: "Vui lòng đăng nhập để xem danh sách bạn bè",
      loadFailed: "Không thể tải danh sách bạn bè",
      cantAddSelf: "Không thể tự kết bạn với chính mình!",
      addSuccess: "Đã kết bạn với {target}!",
      addError: "Có lỗi xảy ra khi kết bạn",
      removeSuccess: "Đã hủy kết bạn với {target}",
      removeError: "Không thể hủy kết bạn",
      copyBrowserError: "Trình duyệt không hỗ trợ sao chép",
      copySuccess: "Đã sao chép vào bộ nhớ tạm",
      title: "Bạn bè",
      desc: "Kết nối với bạn bè để cùng nhau chia sẻ những địa điểm ăn uống thú vị",
      addNewFriend: "Kết bạn mới",
      placeholderUsername: "Nhập tên tài khoản của bạn bè (username)...",
      addBtn: "Thêm",
      biDirectionalInfo: "Kết bạn là mối quan hệ song phương. Khi kết bạn thành công, cả hai sẽ tự động hiển thị trong danh sách của nhau.",
      yourAccount: "Tài khoản của bạn",
      yourAccountDesc: "Chia sẻ thông tin này để bạn bè dễ dàng kết nối với bạn",
      usernameLabel: "Tên tài khoản (username)",
      copyUsernameTooltip: "Sao chép tên tài khoản",
      userIdLabel: "Mã người dùng (User ID)",
      copyUserIdTooltip: "Sao chép mã người dùng",
      friendsListTitle: "Danh sách bạn bè",
      searchPlaceholder: "Tìm bạn bè...",
      loadingText: "Đang tải danh sách...",
      noFriendsTitle: "Chưa có bạn bè",
      noFriendsDesc: "Tìm kiếm và thêm bạn bè bằng tên tài khoản của họ để cùng chia sẻ danh sách địa điểm ăn uống thú vị nhé!",
      noMatchText: "Không tìm thấy bạn bè nào khớp với kết quả tìm kiếm.",
      friendSince: "Bạn bè từ",
      unfriendTooltip: "Hủy kết bạn",
      unfriendConfirmTitle: "Hủy kết bạn",
      unfriendConfirmDesc: "Bạn có chắc chắn muốn hủy kết bạn với {target}? Cả hai sẽ không còn trong danh sách bạn bè của nhau nữa.",
      cancelBtn: "Hủy bỏ",
      confirmDeleteBtn: "Xác nhận xóa",
    },
    groupRecommend: {
      pleaseLogin: "Vui lòng đăng nhập để sử dụng tính năng gợi ý nhóm",
      friendLoadError: "Lỗi khi tải bạn bè:",
      cantLoadFriends: "Không thể tải danh sách bạn bè",
      selectFriendPrompt: "Vui lòng chọn ít nhất 1 người bạn đi cùng!",
      selectLocationPrompt: "Vui lòng định vị vị trí hiện tại của bạn hoặc chọn vùng trên bản đồ để tìm quán lân cận!",
      sessionExpired: "Phiên đăng nhập hết hạn. Vui lòng đăng nhập lại.",
      fetchError: "Không thể lấy gợi ý nhóm",
      recsFound: "Đã tìm thấy các gợi ý phù hợp cho nhóm của bạn!",
      calcError: "Có lỗi xảy ra khi tính toán gợi ý",
      title: "Gợi ý nhóm",
      desc: "Tìm kiếm quán ăn tối ưu nhất cho nhóm bằng cách gộp sở thích và tự động áp dụng các ràng buộc ăn chay/dị ứng của tất cả thành viên.",
      selectMembers: "Chọn thành viên",
      deselectAll: "Bỏ chọn tất cả",
      selectAll: "Chọn tất cả",
      customLocation: "📍 Vị trí tùy chọn (Bản đồ)",
      currentLocation: "📱 Vị trí hiện tại (GPS)",
      restoreGPS: "Khôi phục GPS",
      gpsRestored: "Đã khôi phục về vị trí GPS hiện tại!",
      notPositioned: "Chưa xác định vị trí",
      selectOnMap: "Chọn vùng trên bản đồ trực quan",
      searchRadius: "BÁN KÍNH TÌM KIẾM:",
      loadingFriends: "Đang tải danh sách bạn bè...",
      noFriendsTitle: "Chưa có bạn bè",
      noFriendsDesc: "Bạn cần kết nối với ít nhất một người bạn để có thể thực hiện gợi ý nhóm.",
      addFriendsBtn: "Thêm bạn bè",
      groupBudget: "Ngân sách nhóm",
      unlimited: "Không giới hạn",
      maxLabel: "Tối đa: ",
      loadingSuggestions: "Đang tính toán gợi ý tối ưu...",
      suggestBtn: "Gợi ý cho nhóm ({count} người)",
      disclaimer: "Hệ thống sẽ lấy sở thích của bạn và những người bạn được chọn, kết hợp để tìm các quán ăn phù hợp nhất.",
      appliedConstraints: "Các ràng buộc đã áp dụng",
      vegetarianFilter: "Bộ lọc ăn chay (Vegetarian):",
      activated: "KÍCH HOẠT",
      no: "KHÔNG",
      budgetFilter: "Lọc ngân sách nhóm:",
      radiusFilter: "Bán kính tìm kiếm:",
      excludeAllergies: "Loại trừ thực phẩm gây dị ứng:",
      noAllergiesDetected: "Không phát hiện dị ứng trong nhóm",
      noContains: "Không chứa ",
      analyzingTaste: "Đang phân tích khẩu vị nhóm",
      analyzingTasteDesc: "Đang tính toán vector sở thích trung bình, nạp dữ liệu dị ứng và lọc hơn 150 nhà hàng tương thích...",
      noMatchesFound: "Không tìm thấy quán ăn phù hợp",
      noMatchesDesc: "Các ràng buộc dị ứng hoặc ăn chay của nhóm bạn quá chặt chẽ, hoặc không có quán ăn nào trong phạm vi tìm kiếm phù hợp. Thử thay đổi thành viên xem sao!",
      noResultsYet: "Chưa có kết quả gợi ý",
      noResultsDesc: "Chọn các thành viên đi cùng ở bảng bên trái và nhấp nút Gợi ý cho nhóm để nhận danh sách quán ăn tối ưu từ AI.",
      recsTitle: "🎯 Quán ăn gợi ý cho nhóm",
      resultsCount: " kết quả",
      resultsNarrowed: "Kết quả được thu hẹp",
      resultsNarrowedDesc: "Do nhóm của bạn có các hạn chế khắt khe về dị ứng/ăn chay, số lượng quán ăn an toàn và phù hợp đã giảm xuống dưới 16.",
      mapUpdated: "Đã cập nhật vùng tìm kiếm quán!",
    },
    searchBar: {
      placeholderCompact: "Bạn muốn ăn gì hôm nay?",
      placeholderFull: "Mô tả món ăn bạn muốn...",
      findAgain: "Tìm lại",
      search: "Tìm kiếm"
    },
    budgetSelector: {
      label: "Ngân sách"
    },
    newspaper: {
      title: "Ấm Thực Bản Tin",
      issue: "BẢN TIN SỐ: #W-{day}",
      price: "GIÁ: 0đ (Miễn phí)",
      empty: "Bản tin trống",
      gpsHint: "(Thử cấp quyền vị trí GPS chính xác hơn hoặc nhấn nút Stamp bên dưới để thử lại)",
      stampBtn: "Ấn để xem bản tin ẩm thực khác",
      stampBtnText: "XEM BẢN TIN KHÁC",
      suggestTitle: "Gợi ý món ngon:",
      priceOnly: "Giá chỉ:",
      openTime: "Mở cửa:",
      address: "Địa chỉ:",
      breakfast: "Bữa Sáng (06h - 10h)",
      lunch: "Bữa Trưa (11h - 14h)",
      dinner: "Bữa Tối (17h - 21h)",
      customSlot: "Phần {slot}",
      headlineQuote: "“Wanderbite, bản tin {time} {day}. Thực đơn {adj} cho ngày {weather} tại {city}”"
    },
    userDropdown: {
      login: "Đăng nhập",
      account: "Tài khoản",
      profile: "Hồ sơ cá nhân",
      logout: "Đăng xuất"
    },
    profile: {
      title: "Hồ sơ cá nhân",
      editProfile: "Chỉnh sửa hồ sơ",
      following: "Đang theo dõi",
      followers: "Người theo dõi",
      noTitle: "Chưa có danh hiệu",
      joinLabel: "Tham gia từ {date}",
      joinedFrom: "Tham gia từ",
      loginRequired: "Vui lòng đăng nhập để xem trang cá nhân!",
      badgeSelectTitle: "Click để chọn danh hiệu hiển thị",
      badgeTitleSelect: "Chọn huy hiệu hiển thị",
      badgeChangeTitle: "Click để đổi danh hiệu",
      badgeUnlocked: "Đã mở khóa!",
      badgeZenUnlock: "Ăn chay để mở khóa",
      progress: "Tiến độ",
      foodTaste: "Gu ẩm thực",
      noActivity: "Không có hoạt động gần đây",
      noActivityDesc: "Bạn chưa thực hiện hành động nào trong 3 ngày qua. Hãy bắt đầu trải nghiệm ứng dụng bằng cách xem thông tin, thích món ăn hay lưu trữ vào bộ sưu tập nhé!",
      stats: {
        discoveries: "Khám phá",
        favorites: "Yêu thích",
        reviews: "Đánh giá",
        streak: "Streak"
      },
      badges: {
        "🍜": { label: "Phở Master", description: "Ăn phở như một vị thần" },
        "🌶️": { label: "Cay Vô Đối", description: "Kẻ thách thức mọi cấp độ cay" },
        "🥬": { label: "Thánh Rau", description: "Tín đồ của sự thanh tịnh và chất xơ" },
        "🍦": { label: "Kem Lạnh", description: "Tâm hồn ngọt ngào và mát lạnh" },
        "🥓": { label: "Team Thịt", description: "Không thịt đời không nể" },
        "☕": { label: "Cú Đêm", description: "Thợ săn đồ ăn đêm chuyên nghiệp" },
        "🧘": { label: "Thiền Sư", description: "Ăn chay trường, tâm tịnh như nước" }
      },
      personalization: {
        title: "Khẩu vị & Dinh dưỡng AI",
        favoriteDishes: "Món ăn yêu thích",
        dietaryRestrictions: "Chế độ ăn kiêng",
        allergies: "Dị ứng thực phẩm",
        spicyLevel: "Độ cay ưu tiên",
        budget: "Ngân sách",
        region: "Khu vực",
        age: "Độ tuổi",
        yearsOld: "tuổi",
        notUpdated: "Chưa cập nhật",
        spicyLevelNone: "Không cay",
        spicyLevelMild: "Cay ít (25%)",
        spicyLevelMedium: "Cay vừa (50%)",
        spicyLevelHot: "Cay nồng (75%)",
        spicyLevelExtra: "Siêu cay",
        budgetLow: "Bình dân",
        budgetMedium: "Tầm trung",
        budgetHigh: "Cao cấp"
      },
      modal: {
        title: "Chọn Danh Hiệu Hiển Thị",
        subtitle: "Danh hiệu được chọn sẽ xuất hiện dưới tên và làm đẹp cho Avatar của bạn",
        owned: "Danh hiệu đã sở hữu",
        noBadges: "Bạn chưa mở khóa danh hiệu nào",
        noBadgesDesc: "Hãy tiếp tục tương tác và tìm kiếm để tích lũy huy hiệu nhé!",
        active: "Đang hiển thị",
        locked: "Chưa sở hữu"
      },
      discoveries: "Khám phá",
      favorites: "Yêu thích",
      reviews: "Đánh giá",
      streak: "Streak",
      badgesTitle: "Huy hiệu của bạn",
      culinaryTaste: "Gu ẩm thực",
      aiPersonalization: "Khẩu vị & Dinh dưỡng AI",
      recentActivity: "Hoạt động gần đây",
      noRecentActivity: "Không có hoạt động gần đây",
      noRecentActivityDesc: "Bạn chưa thực hiện hành động nào trong 3 ngày qua.",
      seeMoreActivity: "Xem thêm hoạt động",
      badgeModalTitle: "Chọn Danh Hiệu Hiển Thị",
      badgeModalDesc: "Danh hiệu được chọn sẽ xuất hiện dưới tên và làm đẹp cho Avatar của bạn",
      ownedBadges: "Danh hiệu đã sở hữu ({count})",
      unlockedBadge: "Đang hiển thị",
      notOwnedBadges: "Chưa sở hữu ({count})",
      noOwnedBadges: "Bạn chưa mở khóa danh hiệu nào",
      noOwnedBadgesDesc: "Hãy tiếp tục tương tác và tìm kiếm để tích lũy huy hiệu nhé!",
      clickToChange: "Click để đổi danh hiệu",
      clickToChoose: "Click để chọn danh hiệu",
      favoriteDishes: "Món ăn yêu thích",
      dietary: "Chế độ ăn kiêng",
      allergiesLabel: "Dị ứng của bạn",
      spicyPreference: "Ưu tiên cay",
      budgetLabel: "Ngân sách",
      area: "Khu vực",
      age: "Độ tuổi",
      ageVal: "{age} tuổi",
      notUpdated: "Chưa cập nhật",
      badgeProgress: "Tiến độ: {progress}/{target}",
      badgeUnlockedTooltip: "🌟 Đã mở khóa!",
      badgeLockedTooltip: "🧘 Ăn chay để mở khóa",
      spicyLevelNone: "🌶️ Không cay",
      spicyLevelMild: "🌶️ Cay ít (25%)",
      spicyLevelMedium: "🌶️ Cay vừa (50%)",
      spicyLevelHot: "🌶️ Cay nồng (75%)",
      spicyLevelExtra: "🌶️ Siêu cay",
      budgetLow: "💵 Bình dân",
      budgetMedium: "💵 Tầm trung",
      budgetHigh: "💵 Cao cấp"
    },
    feed: {
      title: "Bảng tin",
      searchFriends: "Tìm kiếm bạn bè...",
      createNew: "Tạo mới",
      forYou: "Dành cho bạn",
      following: "Đang theo dõi",
      loading: "Đang tải bảng tin...",
      noPosts: "Chưa có bài viết nào.",
      noPostsDesc: "Hãy theo dõi thêm foodie hoặc tự chia sẻ trải nghiệm ăn uống của bạn!",
      pleaseLogin: "Vui lòng đăng nhập để đăng bài viết.",
      pleaseLoginStory: "Vui lòng đăng nhập để đăng Story.",
      postSuccess: "Đăng bài thành công!",
      postFailed: "Không thể đăng bài lúc này.",
      connError: "Lỗi kết nối máy chủ.",
      quickCreate: {
        you: "Bạn",
        placeholder: "{username} đang nghĩ gì về món ăn hôm nay?",
        uploadSuccess: "Tải ảnh lên thành công!",
        uploadFailed: "Lỗi tải ảnh lên: {error}",
        tagTitle: "Chọn quán để gắn thẻ",
        searchPlaceholder: "Tìm kiếm quán ăn...",
        noResults: "Không tìm thấy quán nào gần đây.",
        taggedAt: "Tại: {name}",
        actionMedia: "Ảnh / Video",
        actionTag: "Gắn thẻ quán",
        cancel: "Hủy",
        submit: "Đăng bài",
        submitting: "Đang đăng..."
      },
      searchPanel: {
        following: "Đang theo dõi",
        follow: "Theo dõi",
        noMatch: "Không tìm thấy người dùng nào"
      }
    }
  },
  en: {
    sidebar: {
      feed: "Feed",
      discover: "Discover",
      favorites: "Favorites",
      history: "History",
      recommendations: "For You",
      collections: "Collections",
      luckyWheel: "What to Eat?",
      friends: "Friends",
      settings: "Settings",
      itinerary: "Itinerary",
      groupRecommend: "Group Recommendations",
      aiTitle: "Wanderbite AI",
      aiDesc: "Keep your preferences updated so our AI can understand you better!",
      aiBtn: "Update Now",
      guest: "Guest",
      member: "Member",
    },

    appshell: {
      locationTitle: "Click to change your location",
      notPositioned: "Not Located",
      finding: "Locating...",
      systemOk: "System Normal",
      systemError: "System Offline",
      sessionExpired: "Session Expired",
      sessionExpiredDesc: "Your session has expired or is invalid. Please log in again to use all personalized features!",
      goHome: "Back to Home",
      loginAgain: "Log In Again",
      drawerTitle: "Wanderbite",
      drawerFooter: "Powered by AI · Taste of Saigon",
      openMenu: "Open menu",
      itineraryTitle: "View itinerary",
      notLocatedYet: "Not located",
    },
    settings: {
      title: "Settings",
      tabAccount: "Account",
      tabPersonalization: "AI Personalization",
      tabAppearance: "Appearance",
      tabPrivacy: "Privacy",
      accountDesc: "Manage your account settings and security.",
      appearanceDesc: "Customize the application interface to your liking.",
      theme: "Theme",
      themeDesc: "Customize the application interface theme to your style.",
      themeLight: "Light",
      themeDark: "Dark",
      themeSystem: "System",
      themeLightDesc: "Light mode experience",
      themeDarkDesc: "Easy on the eyes",
      themeSystemDesc: "Matches system",
      language: "Language",
      langVi: "Tiếng Việt",
      langEn: "English",
      save: "Save",
      cancel: "Cancel",
      languageTitle: "Language Select",
      languageSelectDesc: "Choose the display language of the application.",
      savingInProgress: "Syncing...",
      updatePreferencesSuccess: "AI taste preferences updated successfully!",
      updatePreferencesFailed: "Update failed!",
      savingError: "An error occurred while saving!",
      favoriteDishesLabel: "Favorite dishes (Select or enter at least 3 items)",
      spicyLabel: "Spicy Preference",
      budgetLabel: "Average Budget",
      dietaryLabel: "Dietary Restrictions",
      allergyLabel: "Food Allergies",
      locationLabel: "Living Area",
      ageLabel: "Age",
      popularSuggestions: "Popular Suggestions:",
      placeholderAge: "Enter age...",
      placeholderLocation: "Example: District 1, HCMC...",
      placeholderDish: "Enter dish name, e.g., Pho...",
      aiPersonalizationTitle: "AI Personalization",
      aiPersonalizationDesc: "Set your taste preferences for the most tailored AI suggestions.",
      syncWithAI: "Update AI Preferences",
      addDishBtn: "Add",
      dishAlreadyAdded: "This dish is already in the list!",
      atLeastThreeDishes: "Please select or enter at least 3 favorite dishes!",
      selectSpicy: "Please select your spicy preference level!",
      selectBudget: "Please select your budget preference!",
      enterLocation: "Please fill in your living area!",
      invalidAge: "Please enter a valid age (13 - 120)!",
      featuresUnderDevelopmentTitle: "Under Development",
      featuresUnderDevelopmentDesc: "This feature will be available soon!",
      editCoverTitle: "Edit Cover Photo",
      editCoverDesc: "Zoom, rotate, or drag the image to center the rectangular crop area (3:1 ratio).",
      zoom: "Zoom",
      rotate: "Rotate",
      confirmCrop: "Confirm Crop",
      editAvatarTitle: "Edit Avatar",
      editAvatarDesc: "Zoom, rotate, or drag the image to center the circular crop area.",
      changePassword: "Change Password",
      changePasswordDesc: "Please enter your current password and your new password.",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      updateBtn: "Update",
      confirmDeleteTitle: "Confirm Account Deletion?",
      confirmDeleteDesc: "This action cannot be undone. All your data, history, and customization will be permanently deleted from the system.",
      confirmDeleteBtn: "Confirm Delete",
      selectAvatarTitle: "Select Avatar",
      uploadPhotoBtn: "Upload Photo",
      uploadedPhotos: "Uploaded Photos",
      noUploadedPhotos: "You haven't uploaded any avatar photos before.",
      viewMore: "View More",
      accountTitle: "Account",
      accountSubtitle: "Manage your account settings and security.",
      coverPhoto: "Cover Photo",
      noCoverPhoto: "No cover photo",
      changeCoverBtn: "Change Cover Photo",
      coverRules: "JPG, PNG max 5MB. Standard 3:1 ratio.",
      avatarLabel: "Avatar",
      avatarRules: "JPG, PNG max 5MB",
      changeAvatarBtn: "Change Photo",
      editBtn: "Edit",
      fullNameLabel: "Full Name",
      fullNamePlaceholder: "Enter full name...",
      saveBtn: "Save",
      copied: "Copied",
      copy: "Copy",
      googleLinkedAccount: "Linked Google Account",
      googleLinkedAccountDesc: "You are using a linked Google account. All security settings and account management will be handled on your Google Profile page.",
      changePasswordSubtitle: "Update your password periodically to protect your account.",
      deleteAccountSubtitle: "This action cannot be undone. All your data on the system will be permanently deleted.",
      privacyTitle: "Privacy",
      privacySubtitle: "Manage your permissions and personal data.",
      allowLocation: "Allow location access",
      allowLocationDesc: "Wanderbite needs this permission to suggest food near you.",
      allowAIPersonalization: "Allow AI personalization data usage",
      allowAIPersonalizationDesc: "Helps AI understand you better to provide highly tailored and accurate suggestions.",
      featureComingSoon: "This feature is coming soon",
      dietaryVegan: "Vegan",
      dietaryVegetarian: "Vegetarian",
      dietaryHalal: "Halal",
      allergyMilk: "Milk",
      allergyEgg: "Egg",
      allergyGluten: "Gluten",
      allergySeafood: "Seafood",
      allergyFish: "Fish",
      allergyPeanut: "Peanut",
      allergySoy: "Soy",
      spicyNone: "0% Spicy",
      spicyMild: "25% Spicy",
      spicyMedium: "50% Spicy",
      spicyHot: "75% Spicy",
      spicyExtraHot: "MAX LEVEL",
      budgetLow: "Budget",
      budgetLowDesc: "Under 50k - Student / Casual",
      budgetMedium: "Mid-range",
      budgetMediumDesc: "50k - 200k - Tasty, good vibes",
      budgetHigh: "Premium",
      budgetHighDesc: "Above 200k - Luxury / Fine dining",
      pleaseLoginAgain: "Please log in again to save changes!",
      sessionExpiredAlert: "Session expired. Please log in again!",
      updateProfileFailed: "Update failed!",
      dbSaveError: "An error occurred while saving to Database!",
      deleteAccountFailed: "Delete account failed!",
      copiedUserId: "Copied User ID!",
      passwordsDoNotMatch: "New password and confirmation password do not match!",
      passwordMinLength: "Password must be at least 8 characters long!",
      passwordChangeSuccess: "Password changed successfully!",
      deleteAccountSuccess: "Account deleted successfully!",
      maxFileSizeError: "File is too large! Please choose an image under 5MB.",
      imageOptimizationError: "Image optimization error:",
      localStoreError: "Local storage error:",
      quotaExceededCleaning: "History quota exceeded, cleaning storage space...",
      cannotWriteLocalStore: "Unable to write to localStorage even after cleaning!",
      avatarUpdateSuccess: "Avatar updated successfully!",
      coverUpdateSuccess: "Cover photo updated successfully!",
      nameUpdateSuccess: "Full name updated successfully!",
      dishAlreadyInList: "This dish is already in the list!",
      popularSuggestionsLabel: "Popular suggestions:"
    },
    home: {
      heroTitle: "WHAT DO YOU WANT ",
      heroTitleSpan: "TO EAT TODAY?",
      heroDesc: "Describe your craving · AI will recommend instantly",
      budgetAuto: "Auto",
      budgetLow: "Budget",
      budgetMedium: "Mid-range",
      budgetHigh: "Premium",
      luckyWheelBtn: "What to eat today? Try our Lucky Wheel!",
      feedBannerTitle: "Explore the Feed 🌟",
      feedBannerDesc: "Join the community to share food experiences!",
      recommendationsTitle: "RECOMMENDED FOR YOU",
      seeMore: "See More",
      noRecommendations: "No recommendations yet, try searching!",
      searchingLocation: "Identifying your location...",
      searchingAI: "AI is analyzing your taste...",
      searchSuccess: "Success! Redirecting...",
      searchError: "Unable to determine your physical location. Please check your GPS permission to continue.",
      connError: "AI connection error. Please try again.",
      healthError: "Cannot connect to server. Please make sure the backend is running.",
      healthDegraded: "System is partially operational — AI Engine not ready or Database disconnected.",
      healthRetry: "Retry",
      describeCravingPlaceholder: "Describe what you crave (e.g., warm noodle soup, rich bone broth, crispy pork...)",
      trendingBBQ: "Top BBQ",
      trendingLateNight: "Late Night Food",
      trendingHealthy: "Healthy Food",
      trendingTeaCoffee: "Milk Tea & Coffee",
      trendingBreadsNoodles: "Breads & Noodles",
      trendingDimsumHotpot: "Dimsum & Hotpot",
    },
    favorites: {
      pleaseLogin: "Please log in to view favorites",
      removedSuccess: "Removed from favorites",
      addedSuccess: "Added to favorites",
      title: "Favorite Dishes",
      desc: "A list of dishes and locations you have saved",
      emptyTitle: "No favorites yet",
      emptyDesc: "Explore and save delicious dishes!",
      exploreBtn: "Explore Now",
      pleaseLoginAction: "Please log in to use this feature",
      cardDetailError: "Cannot open this restaurant's details. Please try again later.",
      sampleResultInfo: "This is a sample result. Try searching to see real restaurants!",
      alreadyInCollection: "This item is already in your collections.",
      deleteBtn: "Delete",
    },
    history: {
      pleaseLogin: "Please log in to view history",
      removedSuccess: "History item removed",
      clearConfirm: "Are you sure you want to clear your entire search history?",
      clearAllSuccess: "Cleared all search history",
      title: "Search History",
      desc: "Review your recently searched dishes",
      clearAllBtn: "Clear All",
      emptyTitle: "No search history yet",
      emptyDesc: "Try searching for a delicious dish now!",
      searchNowBtn: "Search Now",
      budgetLabel: "Budget:",
      budgetAuto: "Auto",
    },
    collections: {
      pleaseLogin: "Please log in to view collections",
      createSuccess: "Collection created successfully",
      deleteSuccess: "Collection deleted successfully",
      removeItemSuccess: "Removed from collection",
      backBtn: "Back",
      savedCount: " saved items",
      emptyTitle: "Empty Collection",
      emptyDesc: "You haven't saved any dishes to this collection yet.",
      exploreBtn: "Explore Now",
      title: "Your Collections",
      desc: "Categorize and save dining locations by your own preferences",
      createBtn: "Create Collection",
      emptyAllTitle: "No collections yet",
      emptyAllDesc: "Create your first collection to save delicious restaurants!",
      createNowBtn: "Create Now",
      locationsCount: "locations",
      deleteCollectionTooltip: "Delete collection",
      createModalTitle: "Create New Collection",
      createModalDesc: "Enter the collection name to store your favorite locations.",
      createModalPlaceholder: "E.g., Weekend Food, Near School...",
      cancelBtn: "Cancel",
      createNewBtn: "Create",
      deleteModalTitle: "Delete Collection",
      deleteModalDesc: "Are you sure you want to delete this collection? This action cannot be undone.",
      deleteConfirmBtn: "Delete",
      addedSuccess: "Added to collection",
      createAndAddedSuccess: "Created and added to collection",
      addToCollection: "Add to collection",
      selectToSave: "Select collection to save",
      noCollectionsYet: "You don't have any collections yet.",
      collectionNamePlaceholder: "Collection name...",
      save: "Save",
      alreadyInCollectionCheck: "Already in collection",
    },
    itinerary: {
      directions: "Directions",
      missingGPSWarning: "Some locations are missing GPS coordinates",
      missingGPSWarningDesc: "distances will not be displayed.",
      stopsCount: "Stops",
      totalDistance: "Total Distance",
      travelTime: "Travel Time",
      stopsCountValue: "stops",
      title: "My Itinerary",
      subtitle: "stops · Drag to reorder",
      clearAll: "Clear All",
      loading: "Loading itinerary...",
      pleaseWait: "Please wait a moment.",
      emptyTitle: "Empty Itinerary",
      emptyDesc: "Click the 🗺 Itinerary button on a restaurant card to add stops here.",
      findPlaces: "Find Places",
      rainWarning: "⚠️ Rain warning at {count} stops",
      rainWarningDesc: "rainy or rain is expected. Remember to bring a raincoat!",
      checkingWeather: "Checking weather at stops...",
      vehicleLabel: "Travel Mode:",
      walking: "Walking",
      riding: "Riding",
      driving: "Driving",
      currentLocation: "Your current location",
      startPoint: "Journey starting point",
      missingGPS: "Missing GPS",
      deleteStopTitle: "Remove from itinerary",
      noDistanceData: "No distance data available",
      openInGoogleMaps: "Open in Google Maps",
      openInGoogleMapsDesc: "This will open the entire route starting from your location on Google Maps",
      clearConfirmTitle: "Clear itinerary?",
      clearConfirmDesc: "All {count} locations will be removed. This action cannot be undone.",
      cancelBtn: "Cancel",
    },
    friends: {
      pleaseLogin: "Please log in to view friends list",
      loadFailed: "Failed to load friends list",
      cantAddSelf: "You cannot add yourself as a friend!",
      addSuccess: "Successfully friended {target}!",
      addError: "An error occurred while adding friend",
      removeSuccess: "Unfriended {target}",
      removeError: "Failed to unfriend",
      copyBrowserError: "Clipboard copy not supported by browser",
      copySuccess: "Copied to clipboard",
      title: "Friends",
      desc: "Connect with friends to share exciting dining spots together",
      addNewFriend: "Add New Friend",
      placeholderUsername: "Enter friend's username...",
      addBtn: "Add",
      biDirectionalInfo: "Friending is bidirectional. Once connected, both users will automatically appear in each other's friends list.",
      yourAccount: "Your Account",
      yourAccountDesc: "Share this information so friends can easily connect with you",
      usernameLabel: "Username",
      copyUsernameTooltip: "Copy username",
      userIdLabel: "User ID",
      copyUserIdTooltip: "Copy User ID",
      friendsListTitle: "Friends List",
      searchPlaceholder: "Search friends...",
      loadingText: "Loading list...",
      noFriendsTitle: "No friends yet",
      noFriendsDesc: "Search and add friends by username to share exciting dining spots!",
      noMatchText: "No friends found matching your search query.",
      friendSince: "Friends since",
      unfriendTooltip: "Unfriend",
      unfriendConfirmTitle: "Unfriend",
      unfriendConfirmDesc: "Are you sure you want to unfriend {target}? You will both be removed from each other's friends list.",
      cancelBtn: "Cancel",
      confirmDeleteBtn: "Confirm Unfriend",
    },
    groupRecommend: {
      pleaseLogin: "Please log in to use group recommendations",
      friendLoadError: "Error loading friends:",
      cantLoadFriends: "Failed to load friends list",
      selectFriendPrompt: "Please select at least 1 friend to go with!",
      selectLocationPrompt: "Please locate your current position or select a region on the map to find nearby restaurants!",
      sessionExpired: "Session expired. Please log in again.",
      fetchError: "Failed to get group recommendations",
      recsFound: "Found suitable recommendations for your group!",
      calcError: "An error occurred while calculating recommendations",
      title: "Group Recommendations",
      desc: "Find the most optimal restaurants for your group by combining preferences and automatically applying vegetarian/allergy constraints of all members.",
      selectMembers: "Select Members",
      deselectAll: "Deselect All",
      selectAll: "Select All",
      customLocation: "📍 Custom Location (Map)",
      currentLocation: "📱 Current Location (GPS)",
      restoreGPS: "Restore GPS",
      gpsRestored: "Restored to current GPS location!",
      notPositioned: "Location not determined",
      selectOnMap: "Select region on interactive map",
      searchRadius: "SEARCH RADIUS:",
      loadingFriends: "Loading friends list...",
      noFriendsTitle: "No friends yet",
      noFriendsDesc: "You need to connect with at least one friend to use group recommendations.",
      addFriendsBtn: "Add Friends",
      groupBudget: "Group Budget",
      unlimited: "Unlimited",
      maxLabel: "Max: ",
      loadingSuggestions: "Calculating optimal suggestions...",
      suggestBtn: "Suggest for group ({count} people)",
      disclaimer: "The system will combine preferences of you and selected friends to find the most suitable restaurants.",
      appliedConstraints: "Applied Constraints",
      vegetarianFilter: "Vegetarian Filter:",
      activated: "ACTIVATED",
      no: "NO",
      budgetFilter: "Group Budget Filter:",
      radiusFilter: "Search Radius Filter:",
      excludeAllergies: "Exclude Food Allergies:",
      noAllergiesDetected: "No allergies detected in the group",
      noContains: "No ",
      analyzingTaste: "Analyzing Group Taste",
      analyzingTasteDesc: "Calculating average preference vectors, loading allergy constraints, and filtering over 150 compatible restaurants...",
      noMatchesFound: "No Suitable Restaurants Found",
      noMatchesDesc: "The allergy or vegetarian constraints of your group are too strict, or there are no suitable restaurants in the search radius. Try changing the members!",
      noResultsYet: "No Recommendations Yet",
      noResultsDesc: "Select the accompanying members on the left panel and click the Suggest for group button to get optimal restaurants from AI.",
      recsTitle: "🎯 Recommended Restaurants for Group",
      resultsCount: " results",
      resultsNarrowed: "Results Narrowed",
      resultsNarrowedDesc: "Due to your group's strict allergy/vegetarian restrictions, the number of safe and suitable restaurants has dropped below 16.",
      mapUpdated: "Search region updated!",
    },
    searchBar: {
      placeholderCompact: "What do you want to eat today?",
      placeholderFull: "Describe the dish you want...",
      findAgain: "Search",
      search: "Search"
    },
    budgetSelector: {
      label: "Budget"
    },
    newspaper: {
      title: "Food Newsletter",
      issue: "ISSUE: #W-{day}",
      price: "PRICE: 0đ (Free)",
      empty: "Empty Newsletter",
      gpsHint: "(Try giving more precise GPS location permission or tap Stamp below to retry)",
      stampBtn: "Tap to view another food newsletter",
      stampBtnText: "VIEW ANOTHER NEWSLETTER",
      suggestTitle: "Delicious suggestion:",
      priceOnly: "Price:",
      openTime: "Open:",
      address: "Address:",
      breakfast: "Breakfast (06:00 - 10:00)",
      lunch: "Lunch (11:00 - 14:00)",
      dinner: "Dinner (17:00 - 21:00)",
      customSlot: "Section {slot}",
      headlineQuote: "“Wanderbite, the {time} {day} edition. A {adj} menu for a {weather} day in {city}”"
    },
    userDropdown: {
      login: "Log in",
      account: "Account",
      profile: "Personal Profile",
      logout: "Log out"
    },
    profile: {
      title: "Personal Profile",
      editProfile: "Edit Profile",
      following: "Following",
      followers: "Followers",
      noTitle: "No badge selected",
      joinLabel: "Joined {date}",
      joinedFrom: "Joined",
      loginRequired: "Please log in to view your profile!",
      badgeSelectTitle: "Click to select active badge",
      badgeTitleSelect: "Select active badge",
      badgeChangeTitle: "Click to change badge",
      badgeUnlocked: "Unlocked!",
      badgeZenUnlock: "Eat veggie to unlock",
      progress: "Progress",
      foodTaste: "Culinary Taste",
      noActivity: "No recent activity",
      noActivityDesc: "You haven't done any actions in the last 3 days. Start by viewing, liking, or adding places to collections!",
      stats: {
        discoveries: "Discoveries",
        favorites: "Favorites",
        reviews: "Reviews",
        streak: "Streak"
      },
      badges: {
        "🍜": { label: "Pho Master", description: "Eating pho like a god" },
        "🌶️": { label: "Spice King", description: "Challenger of all spice levels" },
        "🥬": { label: "Green Saint", description: "Devoted follower of clean eating" },
        "🍦": { label: "Sweet Tooth", description: "Sweet soul, cool as ice" },
        "🥓": { label: "Meat Lover", description: "Life without meat is unimaginable" },
        "☕": { label: "Night Owl", description: "Professional late-night food hunter" },
        "🧘": { label: "Zen Master", description: "Full vegan, mind pure as water" }
      },
      personalization: {
        title: "AI Taste & Nutrition",
        favoriteDishes: "Favorite Dishes",
        dietaryRestrictions: "Dietary Restrictions",
        allergies: "Food Allergies",
        spicyLevel: "Spicy Preference",
        budget: "Budget",
        region: "Area",
        age: "Age",
        yearsOld: "years old",
        notUpdated: "Not updated",
        spicyLevelNone: "No spicy",
        spicyLevelMild: "Mild (25%)",
        spicyLevelMedium: "Medium (50%)",
        spicyLevelHot: "Hot (75%)",
        spicyLevelExtra: "Extra hot",
        budgetLow: "Budget",
        budgetMedium: "Mid-range",
        budgetHigh: "Premium"
      },
      modal: {
        title: "Select Active Badge",
        subtitle: "The selected badge will appear under your name and decorate your avatar",
        owned: "Owned Badges",
        noBadges: "You haven't unlocked any badges yet",
        noBadgesDesc: "Keep interacting and exploring to unlock badges!",
        active: "Displayed",
        locked: "Locked Badges"
      },
      discoveries: "Discoveries",
      favorites: "Favorites",
      reviews: "Reviews",
      streak: "Streak",
      badgesTitle: "Your Badges",
      culinaryTaste: "Culinary Taste",
      aiPersonalization: "AI Taste & Nutrition",
      recentActivity: "Recent Activity",
      noRecentActivity: "No recent activity",
      noRecentActivityDesc: "You haven't done any actions in the last 3 days.",
      seeMoreActivity: "See more activity",
      badgeModalTitle: "Select Active Badge",
      badgeModalDesc: "The selected badge will appear under your name and decorate your avatar",
      ownedBadges: "Owned Badges ({count})",
      unlockedBadge: "Displayed",
      notOwnedBadges: "Locked Badges ({count})",
      noOwnedBadges: "You haven't unlocked any badges yet",
      noOwnedBadgesDesc: "Keep interacting and exploring to unlock badges!",
      clickToChange: "Click to change badge",
      clickToChoose: "Click to choose badge",
      favoriteDishes: "Favorite Dishes",
      dietary: "Dietary Restrictions",
      allergiesLabel: "Your Allergies",
      spicyPreference: "Spicy Preference",
      budgetLabel: "Budget",
      area: "Area",
      age: "Age",
      ageVal: "{age} years old",
      notUpdated: "Not updated",
      badgeProgress: "Progress: {progress}/{target}",
      badgeUnlockedTooltip: "🌟 Unlocked!",
      badgeLockedTooltip: "🧘 Eat veggie to unlock",
      spicyLevelNone: "🌶️ No spicy",
      spicyLevelMild: "🌶️ Mild spicy (25%)",
      spicyLevelMedium: "🌶️ Medium spicy (50%)",
      spicyLevelHot: "🌶️ Hot spicy (75%)",
      spicyLevelExtra: "🌶️ Extremely spicy",
      budgetLow: "💵 Budget",
      budgetMedium: "💵 Mid-range",
      budgetHigh: "💵 Premium"
    },
    feed: {
      title: "Feed",
      searchFriends: "Search friends...",
      createNew: "Create",
      forYou: "For you",
      following: "Following",
      loading: "Loading feed...",
      noPosts: "No posts yet.",
      noPostsDesc: "Follow more foodies or share your own eating experiences!",
      pleaseLogin: "Please log in to publish posts.",
      pleaseLoginStory: "Please log in to publish Story.",
      postSuccess: "Post published successfully!",
      postFailed: "Cannot publish post at this time.",
      connError: "Server connection error.",
      quickCreate: {
        you: "You",
        placeholder: "what are you thinking about food today, {username}?",
        uploadSuccess: "Image uploaded successfully!",
        uploadFailed: "Upload failed: {error}",
        tagTitle: "Select a restaurant to tag",
        searchPlaceholder: "Search restaurants...",
        noResults: "No restaurants found nearby.",
        taggedAt: "At: {name}",
        actionMedia: "Photo / Video",
        actionTag: "Tag restaurant",
        cancel: "Cancel",
        submit: "Post",
        submitting: "Publishing..."
      },
      searchPanel: {
        following: "Following",
        follow: "Follow",
        noMatch: "No users found"
      }
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("vi");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang === "vi" || savedLang === "en") {
      setLanguageState(savedLang);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    // Custom event to alert other windows/components if needed
    window.dispatchEvent(new Event("languageChange"));
  };

  const t = (path: string): string => {
    if (!mounted) return "";
    const keys = path.split(".");
    let current: any = translations[language];

    for (const key of keys) {
      if (current && typeof current === "object" && key in current) {
        current = current[key];
      } else {
        // Fallback to Vietnamese if not found
        let fallback: any = translations["vi"];
        for (const fallbackKey of keys) {
          if (fallback && typeof fallback === "object" && fallbackKey in fallback) {
            fallback = fallback[fallbackKey];
          } else {
            return path;
          }
        }
        return typeof fallback === "string" ? fallback : path;
      }
    }

    return typeof current === "string" ? current : path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
