# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckHealth = channel.unary_unary(
                '/ai.AIService/CheckHealth',
                request_serializer=ai__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ExtractIntentAndVectorize = channel.unary_unary(
                '/ai.AIService/ExtractIntentAndVectorize',
                request_serializer=ai__service__pb2.ExtractIntentRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ExtractIntentResponse.FromString,
                _registered_method=True)
        self.EmbedText = channel.unary_unary(
                '/ai.AIService/EmbedText',
                request_serializer=ai__service__pb2.EmbedTextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.EmbedTextResponse.FromString,
                _registered_method=True)
        self.ReloadRecommendationModel = channel.unary_unary(
                '/ai.AIService/ReloadRecommendationModel',
                request_serializer=ai__service__pb2.ReloadRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.GetLightFMRecommendations = channel.unary_unary(
                '/ai.AIService/GetLightFMRecommendations',
                request_serializer=ai__service__pb2.GetRecommendationsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetRecommendationsResponse.FromString,
                _registered_method=True)
        self.RankCandidates = channel.unary_unary(
                '/ai.AIService/RankCandidates',
                request_serializer=ai__service__pb2.RankRequest.SerializeToString,
                response_deserializer=ai__service__pb2.RankResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckHealth(self, request, context):
        """Check health of AI Engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractIntentAndVectorize(self, request, context):
        """NLP: Intent extraction and vectorization from user query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedText(self, request, context):
        """NLP: Direct embedding generation from text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadRecommendationModel(self, request, context):
        """Admin: Reload Collaborative Filtering model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLightFMRecommendations(self, request, context):
        """Recommendations: Get LightFM collaborative recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RankCandidates(self, request, context):
        """Ranking: Rerank candidates using LambdaMART
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=ai__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ExtractIntentAndVectorize': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractIntentAndVectorize,
                    request_deserializer=ai__service__pb2.ExtractIntentRequest.FromString,
                    response_serializer=ai__service__pb2.ExtractIntentResponse.SerializeToString,
            ),
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=ai__service__pb2.EmbedTextRequest.FromString,
                    response_serializer=ai__service__pb2.EmbedTextResponse.SerializeToString,
            ),
            'ReloadRecommendationModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadRecommendationModel,
                    request_deserializer=ai__service__pb2.ReloadRequest.FromString,
                    response_serializer=ai__service__pb2.ReloadResponse.SerializeToString,
            ),
            'GetLightFMRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLightFMRecommendations,
                    request_deserializer=ai__service__pb2.GetRecommendationsRequest.FromString,
                    response_serializer=ai__service__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'RankCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.RankCandidates,
                    request_deserializer=ai__service__pb2.RankRequest.FromString,
                    response_serializer=ai__service__pb2.RankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/CheckHealth',
            ai__service__pb2.HealthCheckRequest.SerializeToString,
            ai__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractIntentAndVectorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ExtractIntentAndVectorize',
            ai__service__pb2.ExtractIntentRequest.SerializeToString,
            ai__service__pb2.ExtractIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/EmbedText',
            ai__service__pb2.EmbedTextRequest.SerializeToString,
            ai__service__pb2.EmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadRecommendationModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ReloadRecommendationModel',
            ai__service__pb2.ReloadRequest.SerializeToString,
            ai__service__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLightFMRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetLightFMRecommendations',
            ai__service__pb2.GetRecommendationsRequest.SerializeToString,
            ai__service__pb2.GetRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RankCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/RankCandidates',
            ai__service__pb2.RankRequest.SerializeToString,
            ai__service__pb2.RankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
